services:
  data_ingestion:
    build: .
    volumes:
      - analytics_data:/analytics

  duckdb_cli:
    build: .
    command: tail -f /dev/null  # Keeps the container running to run duckdb cli manually
    depends_on:
      - data_ingestion
    volumes:
      - analytics_data:/analytics

#to persist data so duck_cli can use retail.db from data_ingestion
volumes:
  analytics_data:
